    name: reusable deployment
    on:
      workflow_call:
        inputs:
          artifact-name:
            description: 'Name of the artifact to download'
            required: false
            default: 'dist-files'
            type: string
        outputs:
          artifact-name:
            description: 'Name of the artifact to download'
            value: ${{ inputs.artifact-name }}
        # secrets:
        #   deploy-token:
        #     description: 'Token for deployment'
        #     required: true
    jobs:
      deploy:
        outputs:
          outcome: ${{ steps.deploy.outcome }}
        runs-on: ubuntu-latest
        steps:
          - name: Get build artifacts
            uses: actions/download-artifact@v4
            with:
              name: ${{ inputs.artifact-name }}
          - name: Output contents
            run: ls
          - name: Deploy
            id: deploy
            run: echo "Deploying..."
          - name: Output deployment information
            run: echo "set-output name=artifact-name::${{ inputs.artifact-name }}"
    