    name: reusable deployment
    on:
      workflow_call:
        inputs:
          artifact-name:
            description: 'Name of the artifact to download'
            required: false
            default: 'dist-files'
            type: string
        outputs:
          result:
            description: 'the result of the deployment'
            value: ${{ jobs.deploy.outputs.outcome}}
        # secrets:
        #   deploy-token:
        #     description: 'Token for deployment'
        #     required: true
    jobs:
      deploy:
        outputs:
          outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
          - name: Get build artifacts
            uses: actions/download-artifact@v4
            with:
              name: ${{ inputs.artifact-name }}
          - name: Output contents
            run: ls
          - name: Deploy
            id: deploy
            run: echo "Deploying..."
          - name: Output deployment information
            id: set-result
            run: echo "::set-output name=step-result::success"